--- 
components: 
  schemas: 
    WasteContainerIsle: 
      $ref: "https://smart-data-models.github.io/dataModel.WasteManagement/WasteContainerIsle/model.yaml#/WasteContainerIsle"
info: 
  description: |
      A geographical area which keeps one or more waste containers.
  title: WasteContainerIsle
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - WasteContainerIsle
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.WasteManagement/WasteContainerIsle/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.WasteManagement/WasteContainerIsle/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
